<?php

/**
 * AJAX request handlers for WP Send Message admin actions.
 *
 * Registers wp_ajax_* hooks for logged-in admin users.
 * All handlers verify nonces before processing submitted data.
 */

namespace WpSendMessage\Includes;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Class Ajax
 *
 * Singleton that registers and handles admin-ajax.php endpoints.
 * Currently supports adding a new contact via the contacts page modal form.
 */
class Ajax
{
    /**
     * Singleton instance holder.
     *
     * @var Ajax|null
     */
    private static $instance = null;

    /**
     * Plugin identifier prefix (reserved for future use; not currently used in handlers).
     *
     * @var string
     */
    private string $prefix = 'wpsm';

    /**
     * Menu registry placeholder (unused in this class; may be legacy from copy-paste).
     *
     * @var array
     */
    private array $menus = [];

    /**
     * Returns the singleton Ajax instance.
     *
     * @return Ajax
     */
    public static function instance(): Ajax
    {
        if (is_null(self::$instance)) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Registers WordPress AJAX action hooks on construction.
     *
     * wp_ajax_{action} only fires for authenticated users (no wp_ajax_nopriv_ variant).
     *
     * @return void
     */
    public function __construct()
    {
        // Maps to admin-ajax.php?action=add-contact (also set via hidden form input).
        add_action('wp_ajax_add-contact', [$this, 'add_contact']);
    }

    /**
     * Validates and processes the "Add Contact" form submission.
     *
     * Expects POST/REQUEST fields: name, phone, email, _wpnonce, _wp_http_referer.
     * Returns JSON via wp_send_json_success() or wp_send_json_error().
     *
     * NOTE: Currently validates only — does not persist data to the database yet.
     *
     * @return void Terminates execution via wp_send_json_* (never returns normally).
     */
    public function add_contact(): void
    {
        // Retrieve and sanitize the WordPress nonce generated by wp_nonce_field('add-contact').
        $nonce = sanitize_text_field($_REQUEST['_wpnonce']);

        // Reject request if nonce is missing, expired, or tampered with.
        if (!wp_verify_nonce($nonce, 'add-contact')) {
            wp_send_json_error(
                __('There was an error while submiting a new contact.', 'wp-send-message'),
            );
        }

        // Capture the referring admin page URL for potential redirect or logging.
        $referer = sanitize_text_field($_REQUEST['_wp_http_referer']);

        // Collect validation error messages to return as a JSON array.
        $errors = [];

        // Name is required for every contact record.
        $name = sanitize_text_field($_REQUEST['name']);

        if ($name == '') {
            $errors[] = __('The name field is required.', 'wp-send-message');
        }

        // Phone and email are optional individually, but at least one must be provided.
        $phone = sanitize_text_field($_REQUEST['phone'] ?? '');
        $email = sanitize_text_field($_REQUEST['email'] ?? '');

        if ($phone == '' && $email == '') {
            $errors[] = __('One of phone or email field is required.', 'wp-send-message');
        }

        // --- Iranian mobile number normalization ---
        // Strip whitespace and non-numeric characters except leading '+'.
        $phone = trim($phone);
        $phone = preg_replace('/[^0-9+]/', '', $phone);

        // Convert international/country-code formats to local 09xxxxxxxxx format.
        if (strpos($phone, '+98') === 0) {
            // +98912xxxxxxx → 0912xxxxxxx
            $phone = '0' . substr($phone, 3);
        } elseif (strpos($phone, '0098') === 0) {
            // 0098912xxxxxxx → 0912xxxxxxx
            $phone = '0' . substr($phone, 4);
        } elseif (strpos($phone, '98') === 0) {
            // 98912xxxxxxx → 0912xxxxxxx
            $phone = '0' . substr($phone, 2);
        } elseif (strpos($phone, '9') === 0) {
            // 912xxxxxxx → 0912xxxxxxx (missing leading zero)
            $phone = '0' . $phone;
        }

        // Validate normalized number against Iranian mobile pattern: 09 + 9 digits.
        // NOTE: This runs even when $phone is empty (email-only submission) — known bug.
        if (preg_match('/^09\d{9}$/', $phone)) {
            $phone = $phone; // Valid; no-op assignment preserves normalized value.
        } else {
            $errors[] = __('The phone number is not a valid mobile number.', 'wp-send-message');
        }

        // Validate email format only when a value was submitted.
        if ($email !== '' && !filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $errors[] = __('The email format is invalid.', 'wp-send-message');
        }

        // Return all validation errors at once if any rule failed.
        if (count($errors) > 0) {
            wp_send_json_error($errors);
        }

        // Return sanitized data on success.
        // TODO: Insert record into {prefix}send_message_contacts table before responding.
        wp_send_json_success([
            'name'    => $name,
            'phone'   => $phone,
            'email'   => $email,
            'referer' => $referer,
        ]);
    }
}
